# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "vi-VN"

reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master
      - develop
  
  path_filters:
    # Bỏ qua các thư mục không cần review
    - "!**/node_modules/**"
    - "!**/bin/**"
    - "!**/obj/**"
    - "!**/*.min.js"
    - "!**/*.min.css"
    - "!**/wwwroot/libs/**"
    - "!**/.angular/**"
    - "!**/dist/**"
  
  path_instructions:
    - path: "src/**/*.cs"
      instructions: |
        Review C# code following ABP Framework best practices.
        Check for proper dependency injection, entity framework usage, and domain-driven design patterns.
    
    - path: "mobile/**/*.tsx"
      instructions: |
        Review React Native TypeScript code.
        Check for proper state management, component optimization, and TypeScript types.
    
    - path: "mobile/**/*.ts"
      instructions: |
        Review TypeScript code for API calls, utilities, and services.
        Ensure proper error handling and type safety.

chat:
  auto_reply: true

early_access: false
