// ============================================================
// EXAMPLE: Aggregate Root Entity — based on ABP official docs
// Location: src/Knowledtree.Domain/Books/Book.cs
// ============================================================

using System;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using Volo.Abp;
using Volo.Abp.Domain.Entities.Auditing;

namespace Knowledtree.Books;

/// <summary>
/// Book is an Aggregate Root.
/// - Inherits FullAuditedAggregateRoot for full audit trail (Creation, Modification, Deletion).
/// - Uses Guid as the primary key.
/// </summary>
public class Book : FullAuditedAggregateRoot<Guid>
{
    /// <summary>Title — protected by private setter, changed via SetTitle().</summary>
    public virtual string Title { get; private set; }

    /// <summary>Description — can be changed directly, nullable.</summary>
    public virtual string? Description { get; set; }

    /// <summary>Price — public setter for simple values.</summary>
    public virtual decimal Price { get; set; }

    /// <summary>
    /// Reference to another Aggregate Root (Author) — by ID only, no navigation property.
    /// </summary>
    public virtual Guid AuthorId { get; private set; }

    /// <summary>Sub-collection of tags (child entities).</summary>
    public virtual Collection<BookTag> Tags { get; protected set; }

    /// <summary>
    /// Protected parameterless constructor — required by EF Core / ORMs.
    /// </summary>
    protected Book() { }

    /// <summary>
    /// Primary constructor — validates required fields on creation.
    /// Id should be generated by the calling code using IGuidGenerator.
    /// </summary>
    public Book(
        Guid id,
        [NotNull] string title,
        Guid authorId,
        decimal price,
        string? description = null)
        : base(id)
    {
        Title = Check.NotNullOrWhiteSpace(title, nameof(title), maxLength: BookConsts.MaxTitleLength);
        AuthorId = authorId;
        Price = price;
        Description = description;
        Tags = new Collection<BookTag>(); // Always initialize sub-collections
    }

    /// <summary>
    /// Setter method for Title — validates and returns this for fluent API.
    /// </summary>
    public virtual Book SetTitle([NotNull] string title)
    {
        Title = Check.NotNullOrWhiteSpace(title, nameof(title), maxLength: BookConsts.MaxTitleLength);
        return this;
    }

    /// <summary>
    /// Assigns to a different author.
    /// </summary>
    public virtual Book SetAuthor(Guid authorId)
    {
        AuthorId = authorId;
        return this;
    }
}

// ============================================================
// EXAMPLE: Child Entity (non-aggregate-root) — no repository needed
// Location: src/Knowledtree.Domain/Books/BookTag.cs
// ============================================================

/// <summary>
/// BookTag is a child entity of Book aggregate.
/// Uses composite key (no single Id).
/// </summary>
public class BookTag : Volo.Abp.Domain.Entities.Entity
{
    public virtual Guid BookId { get; private set; }
    public virtual Guid TagId { get; private set; }

    protected BookTag() { }

    public BookTag(Guid bookId, Guid tagId)
    {
        BookId = bookId;
        TagId = tagId;
    }

    public override object[] GetKeys()
    {
        return new object[] { BookId, TagId };
    }
}
